management.endpoints.web.base-path: /
management.endpoints.enabled-by-default: false
management.endpoint.health.enabled: true
management.endpoint.health.show-details: always
management.health.db.enabled: false
management.health.diskspace.enabled: true

server.port: 8081


#
#spring.jpa.hibernate.ddl-auto: none
#
#spring.datasource:
#  url: 'jdbc:mysql://localhost/security?useSSL=false'
#  username: root
#  password: rootpwd

